import { Metadata } from 'next'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'about',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <div className='mt-{200px}'>
      <p className='font-bold text-center uppercase text-3xl'>about</p>
    </div>
  )
}